config/routes.rb
Rails.application.routes.draw do

  root to: "web/investors#index"
  scope module: "web" do
    resources :investors, only: [:index, :new, :create, :edit, :update]
    resources :borrowers, only: [:index, :new, :create]
  end

  namespace :web_api, format: :json do
    resources :investors, only: [:show]
  end

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base

  belongs_to :investor

end

app/models/investor.rb
class Investor < ActiveRecord::Base

  has_many :borrowers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Concerns::FlashService
  
  protect_from_forgery with: :exception
end

app/controllers/concerns/flash_service.rb
module Concerns
  module FlashService
    def f(key, options = {})
      scope = [:flash]
      scope << params[:controller].split("/")
      scope << params[:action]

      if options.present?
        options.merge!({scope: scope}) unless options[:scope]
        msg = t(key, options)
      else
        msg = t(key, scope: scope)
      end

      Rails.logger.debug("flash: #{msg}".colorize(:green))

      if options[:now]
        flash.now[key] = msg
      else
        flash[key] = msg
      end
    end
  end
end

app/controllers/web/borrowers_controller.rb
class Web::BorrowersController < ApplicationController

  def index
    @borrowers = Borrower.all
  end

  def new
    @borrower = Borrower.new
  end

  def create
    @borrower = Borrower.new(borrower_params)
    if @borrower.save
      f(:success)
      redirect_to borrowers_path
    else
      f(:error)
      render :new
    end
  end

  def edit
    @borrower = Borrower.find(params[:id])
  end

  def update
    @borrower = Borrower.find(params[:id])

    if @borrower.update borrower_params
      f(:success)
      redirect_to borrowers_path
    else
      f(:error)
      render :edit
    end
  end

  def borrower_params
    params.require(:borrower).permit(:investor_id, :payments)
  end

end

app/controllers/web/investors_controller.rb
class Web::InvestorsController < ApplicationController

  def index
    @investors = Investor.all
  end

  def new
    @investor = Investor.new
  end

  def create
    @investor = Investor.new(investor_params)
    if @investor.save
      f(:success)
      redirect_to investors_path
    else
      f(:error)
      render :new
    end
  end

  def edit
    @investor = Investor.find(params[:id])
  end

  def update
    @investor = Investor.find(params[:id])

    if @investor.update investor_params
      f(:success)
      redirect_to investors_path
    else
      f(:error)
      render :edit
    end
  end

  def investor_params
    params.require(:investor).permit(:amount, :period, :rate, :expire_rate)
  end

end

app/controllers/web_api/application_controller.rb
class WebApi::ApplicationController < ApplicationController

  respond_to :json

end

app/controllers/web_api/investors_controller.rb
class WebApi::InvestorsController < WebApi::ApplicationController
  respond_to :json

  def show
    @investor = Investor.find(params[:id])
    respond_with @investor, include: :borrowers, location: nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path, link_class, li_class)
    if request.fullpath == link_path
      class_name = "#{li_class} active";
    elsif link_path != '/' && request.fullpath.start_with?(link_path)
      class_name = "#{li_class} active";
    else
      class_name = li_class;
    end

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path, :class => link_class
    end
  end

end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_flash_messages
    messages = ""
    if (msg = flash[:notice] || flash[:success])
      messages = render "bootstrap/notice", message: msg
    end
    messages += render "bootstrap/alert", message: flash[:alert] if flash[:alert]
    messages += render "bootstrap/error", message: flash[:error] if flash[:error]
    messages.html_safe
  end
end

app/views/bootstrap/_alert.html.haml
.card.card-inverse.card-warning
  .card-block
    = message.html_safe

app/views/bootstrap/_error.html.haml
.card.card-inverse.card-danger
  .card-block
    = message.html_safe

app/views/bootstrap/_notice.html.haml
.card.card-inverse.card-success
  .card-block
    = message.html_safe

app/views/layouts/application.html.haml
%html
  %head
    %titleCreditorIncomeCalc
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/web/nav'
    .container-fluid.container-max-width
      = bootstrap_flash_messages
      = yield

app/views/layouts/web/_nav.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  .collapse.navbar-collapse
    %ul.navbar-nav
      = nav_link(t('investors'), investors_path, 'nav-link', 'nav-item')
      = nav_link(t('borrowers'), borrowers_path, 'nav-link', 'nav-item')

app/views/web/borrowers/_form.html.haml
= simple_form_for @borrower, url: url, html: { method: method } do |f|
  .row
    .col-md-6
      %br
      .dropdown
        = f.input :payments, as: :hidden, input_html: {id: 'borrower-payments'}
        = f.collection_select :investor_id, Investor.all, :id, :id, {prompt: t('choose_investor')}, {id: 'investor', class: "form-control"}
      %br
      .investor-data
      %br
    .col-md-12
      .payments

  .form-group
    = f.button :submit, class: 'btn btn-primary', id: 'borrower-btn', disabled: true


:javascript
  document.addEventListener("turbolinks:load", function(event) {
    $('#investor').change(function(event){
      investorId = document.getElementById('investor').value;
      if (investorId) {
        getInvestorData(investorId).success(function(investorData){
          $('.investor-data').empty();
          $('.investor-data').append(investorTemplate(investorData));
          $('.payments').empty();
          for(var i = 0; i < investorData.period; i++) {
            $('.payments').append(paymentCards(i+1));
          }
        });
      } else {
        $('.payments').empty();
        $('.investor-data').empty();
      }
    });
  });

  function getInvestorData(investorId){
    return $.ajax({
      url: `/web_api/investors/${investorId}`,
      method: 'GET'
    });
  }

  function handlePaymentChange(monthNumber){
    paymentsData = {};
    paymentType = $(`input[name="payment-month-${monthNumber}"]:checked`).val();
    $(`#summary-${monthNumber}`).empty();
    investorId = document.getElementById('investor').value;
    if (investorId) {
      getInvestorData(investorId).success(function(investorData){
        for(var i = 0; i < investorData.period; i++) {
          paymentsData[`${i+1}`] = $(`input[name="payment-month-${i+1}"]:checked`).val();
          paymentsJson = JSON.stringify(paymentsData);
          $('#borrower-payments').val(paymentsJson);
        }
        checkForSubmit(investorData);
        displayIfLastPayRemoved(investorData);

        monthlyPercent = investorData.amount*investorData.rate/100/12;
        monthlyBadPercent = investorData.amount*investorData.expire_rate/100/12;

        monthlyAmount = investorData.amount/investorData.period;

        monthlyTotal = monthlyAmount + monthlyPercent;
        monthlyBadTotal = monthlyAmount + monthlyBadPercent;

        switch(paymentType) {
          case 'inTime':
            $(`#summary-${monthNumber}`).append(monthlyTotal);
            break;
          case 'badTime':
            $(`#summary-${monthNumber}`).append(monthlyBadTotal);
            break;
          default:
            for(var i = monthNumber; i < investorData.period; i++) {
              $(`.full-card-${i+1}`).addClass( "hide-item" );
              $(`#summary-${i+1}`).empty();
              $(`input[name="payment-month-${i+1}"]`).prop('checked', false);
            }
            restPayment = investorData.amount - monthlyAmount * (monthNumber - 1) + monthlyPercent;
            $(`#summary-${monthNumber}`).append(restPayment);
        }
      });
    }
  }

  function checkForSubmit(investorData){
    flag = 0;
    for(var i = 1; i <= investorData.period; i++) {
      if ($(`input[name="payment-month-${i}"]:checked`).val() == 'lastPay'){
        document.getElementById("borrower-btn").disabled = false;
        break;
      } else if (!$(`input[name="payment-month-${i}"]:checked`).val()) {
        flag = 1;
        document.getElementById("borrower-btn").disabled = true;
        break;
      }
    }
    if (flag == 0) {
      document.getElementById("borrower-btn").disabled = false;
    }
    console.log(flag)
  }

  function displayIfLastPayRemoved(investorData) {
    flag = 0;
    for(var i = 1; i <= investorData.period; i++) {
      if ($(`input[name="payment-month-${i}"]:checked`).val() == 'lastPay') {
        flag = 1;
      }
    }
    if (flag == 0) {
      for(var i = 1; i <= investorData.period; i++) {
        $(`.full-card-${i}`).removeClass( "hide-item" );
      }
    }
  }

  function paymentCards(month){
    return template = [
      `<div class="col-md-4 float-left mb-3 full-card-${month}">`,
        '<div class="card">',
          '<div class="card-header">',
            'Месяц '+ month +'<br>',
          '</div>',
          '<div class="card-block">',
            `<blockquote class="card-blockquote">`,
              `<label><input type="radio" onchange="handlePaymentChange(${month});" name="payment-month-${month}" value="inTime">Оплата вовремя</label><br>`,
              `<label><input type="radio" onchange="handlePaymentChange(${month});" name="payment-month-${month}" value="badTime">Оплата с просрочкой</label><br>`,
              `<label><input type="radio" onchange="handlePaymentChange(${month});" name="payment-month-${month}" value="lastPay">Досрочная оплата</label><br><br>`,
              `<p>Выплата: <b id="summary-${month}"></b></p>`,
            '</blockquote>',
          '</div>',
        '</div>',
      '</div>'
    ].join("\n");
  }

  function investorTemplate(investorData){
    monthlyPercent = investorData.amount*investorData.rate/100/12;
    monthlyAmount = investorData.amount/investorData.period;
    monthlyTotal = monthlyAmount + monthlyPercent;
    return template = [
      '<div>',
        '<h2>Информация об инвеcторе:</h2><br>',
        'Сумма: ' + investorData.amount + '<br>',
        'Срок (мес): ' + investorData.period + '<br>',
        'Ставка годовых: ' + investorData.rate + '%<br>',
        'Ставка годовых при просрочке: ' + investorData.expire_rate + '%<br>',
        'Ежемесячный по долгу: ' + monthlyAmount + '<br>',
        'Ежемесячный по процентам: ' + monthlyPercent + '<br>',
        'Общий ежемесячный: ' + monthlyTotal + '<br>',
        'Сумма выплаты: ' + investorData.period*monthlyTotal + '<br>',
      '</div>'
    ].join("\n");
  }

app/views/web/borrowers/edit.html.haml
.page-header
  %h1= t('.edit')
  %br
= render 'form', url: borrower_path(@borrower), method: "PUT"

app/views/web/borrowers/index.html.haml
.row
  .col-md-12
    .page-header
      %h1= t('.title')

    %br
    %table.table.table-striped
      %thead
        %tr
          %th= Borrower.human_attribute_name(:number)
          %th= Borrower.human_attribute_name(:payments)
      %tbody
        - @borrowers.each do |borrower|
          %tr
            %td= borrower.id
            %td= borrower.payments
            %td{ title: "" }
  
    .form-actions
      = link_to t(".add"), new_borrower_path, class: 'btn btn-primary'

app/views/web/borrowers/new.html.haml
.page-header
  %h1= t('.add')
= render 'form', url: borrowers_path, method: "POST"

app/views/web/investors/_form.html.haml
= simple_form_for @investor, url: url, html: { method: method } do |f|
  .row
    .col-md-6
      = f.input :id, as: :hidden, input_html: {id: 'investor-number'}
      = f.input :amount, input_html: {id: 'investor-amount'}
      = f.input :period, input_html: {id: 'investor-period'}
      = f.input :rate, input_html: {id: 'investor-rate'}
      = f.input :expire_rate, input_html: {id: 'investor-expire-rate'}
    .col-md-6
      .investor-calc
  .form-group
    = f.button :submit, class: 'btn btn-primary'

app/views/web/investors/edit.html.haml
.page-header
  %h1= t('.edit')
= render 'form', url: investor_path(@investor), method: "PUT"

:javascript
  document.addEventListener("turbolinks:load", function(event) {
    $('#investor-amount,#investor-period,#investor-rate,#investor-expire-rate').change(function(event){
      investorId = document.getElementById('investor-number').value;
      if (investorId) {
        $('.investor-calc').empty();
        getInvestorData(investorId).success(function(investorData){
          $('.investor-calc').append(investorTemplate(investorData));
        });
      }
    });
  });

  function getInvestorData(investorId){
    return $.ajax({
      url: `/web_api/investors/${investorId}`,
      method: 'GET'
    });
  }

  function investorTemplate(investorData){
    borrowerCount = investorData.borrowers.length;
    investorAmount = document.getElementById('investor-amount').value;
    investorPeriod = document.getElementById('investor-period').value;
    investorRate = document.getElementById('investor-rate').value;
    investorExpireRate = document.getElementById('investor-expire-rate').value;
    realIncomePercent = calcRealIncome(investorData, investorAmount, investorRate, investorExpireRate);

    theoryIncome = investorAmount * investorRate / 12 * investorPeriod / investorAmount / 6 * 12;
    theoryIncomeMoney = investorAmount * borrowerCount * (1 + theoryIncome/100);
    realIncomeMoney = investorAmount * borrowerCount * (1 + realIncomePercent/100);

    return template = [
      '<div>',
        '<h2>Информация об инвеcторе:</h2><br>',
        'Количество заемщиков: ' + borrowerCount + '<br>',
        'Годовая доходность(%) оптимистично ' + theoryIncome + '%<br>',
        'Годовая доходность(сумма) оптимистично ' + theoryIncomeMoney + '<br><br>',
        'Годовая доходность(%) релистично ' + realIncomePercent + '%<br>',
        'Годовая доходность(сумма) релистично ' + realIncomeMoney + '<br>',
      '</div>'
    ].join("\n");
  }

  function calcRealIncome(investorData, investorAmount, investorRate, investorExpireRate){
    badCount = 0;
    goodCount = 0;
    $.each(investorData.borrowers, function(key, value) {
      $.each(JSON.parse(value.payments), function(k, v) {
        if (v == 'badTime') {
          badCount += 1;
        } else {
          goodCount +=1;
        }
      });
    });
    persentIncome = (investorAmount * investorRate / 12 * goodCount) + (investorAmount * investorExpireRate / 12 * badCount);
    mainIncome = (investorData.borrowers.length * investorAmount);
    realIncome = persentIncome / mainIncome / 6 * 12;
    return realIncome;
  }

app/views/web/investors/index.html.haml
.row
  .col-md-12
    .page-header
      %h1= t('.title')

    %br
    %table.table.table-striped
      %thead
        %tr
          %th= Investor.human_attribute_name(:number)
          %th= Investor.human_attribute_name(:amount)
          %th= Investor.human_attribute_name(:period)
          %th= Investor.human_attribute_name(:rate)
          %th= Investor.human_attribute_name(:expire_rate)
          %th= t('edit')
      %tbody
        - @investors.each do |investor|
          %tr
            %td= investor.id
            %td= investor.amount
            %td= investor.period
            %td= investor.rate
            %td= investor.expire_rate
            %td{ title: "" }
              = link_to edit_investor_path(investor) do
                %i.fa.fa-pencil

    .form-actions
      = link_to t(".add"), new_investor_path, class: 'btn btn-primary'

app/views/web/investors/new.html.haml
.page-header
  %h1= t('.add')
= render 'form', url: investors_path, method: "POST"